DELETE FROM auditoria_global;
DELETE FROM ovyva_mensagens;
DELETE FROM ovyva_conversas;
DELETE FROM leads_historico;
DELETE FROM leads;
DELETE FROM evolucoes;
DELETE FROM prescricoes;
DELETE FROM harmonizacoes;
DELETE FROM termos_consentimento;
DELETE FROM documentos_paciente;
DELETE FROM anamneses;
DELETE FROM consultas;
DELETE FROM procedimentos;
DELETE FROM lancamentos;
DELETE FROM estoque_movimentacoes;
DELETE FROM pedidos_compra;
DELETE FROM procedimento_insumos;
DELETE FROM produtos_estoque;
DELETE FROM whatsapp_instancias;
DELETE FROM pacientes;
DELETE FROM profiles WHERE role != 'superadmin';
DELETE FROM clinicas;
UPDATE profiles SET clinica_id = NULL WHERE role = 'superadmin';
